steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-north1-docker.pkg.dev/$PROJECT_ID/testing/test-sapper:$BRANCH_NAME-$SHORT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-north1-docker.pkg.dev/$PROJECT_ID/testing/test-sapper:$BRANCH_NAME-$SHORT_SHA']

# Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'test-sapper'
    - '--image'
    - 'europe-north1-docker.pkg.dev/$PROJECT_ID/testing/test-sapper:$BRANCH_NAME-$SHORT_SHA'
    - '--region'
    - 'europe-north1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
  images:
  - 'europe-north1-docker.pkg.dev/$PROJECT_ID/testing/test-sapper:$BRANCH_NAME-$SHORT_SHA'