steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-north1-docker.pkg.dev/$PROJECT_ID/testing/test-sapper:$COMMIT_SHA', '.'] # or $SHORT_SHA

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-north1-docker.pkg.dev/$PROJECT_ID/test/test-sapper:$COMMIT_SHA']